### ISSUE TITLE
gem cannot be installed

### ISSUE THREAD

**Issue by MothOnMars** [18F/omniauth_login_dot_gov#17]
**Steps:**
1.  create a new project directory:  
```
mkdir test_omniauth_login_dot_gov
cd test_omniauth_login_dot_gov
```
2.  Create a Gemfile that includes the `omniauth_login_dot_gov` gem per the README:
```
source 'https://rubygems.org'

gem 'omniauth_login_dot_gov', :git => 'https://github.com/18f/omniauth_login_dot_gov.git'
```
3. attempt to install the gem:
```
bundle
```

**Expected Results:**
* the gem is successfully installed

**Actual Results:**
An error is reported:
```
$ bundle
Fetching https://github.com/18f/omniauth_login_dot_gov.git
Fetching gem metadata from https://rubygems.org/
Could not find gem 'omniauth_login_dot_gov' in https://github.com/18f/omniauth_login_dot_gov.git (at master@e38c62d).
The source does not contain any versions of 'omniauth_login_dot_gov'
```

We originally encountered the error when attempting to update the `omniauth_login_dot_gov` gem in the [search-gov](https://github.com/GSA/search-gov) repo. We are working around it temporarily by specifying the commit from our original gem installation:
```
gem 'omniauth_login_dot_gov', git: 'https://github.com/18f/omniauth_login_dot_gov.git',
  ref: '08ce9b5322efb2d82b2df3f6d774308c4028ee6c'
```

**Comment by zachmargolis** [comment]
we recently switched the gem to use `main` instead of the `master` branch, can you try adding `branch: 'main'` instead?

**Comment by MothOnMars** [comment]
Thanks, that did the trick. I've opened a PR to update the instructions: https://github.com/18F/omniauth_login_dot_gov/pull/18
