### ISSUE TITLE
intermittent login failures due to JWT::ImmatureSignature

### ISSUE THREAD

**Issue by MothOnMars** [18F/omniauth_login_dot_gov#26]
Our team has encountered intermittent login failures related to the error `JWT::ImmatureSignature Signature nbf has not been reached` in multiple environments. Sample log line:
```
[2022-11-02T20:07:16.537968 #1991] INFO -- : [ba9b0ed5-b9a2-44a6-ad75-6febaa90eab8] Started GET "/auth/failure?message=Signature+nbf+has+not+been+reached...
```
The issue is that the gem is calling `JWT.decode` without any time leeway, which results in the sign-in token being invalidated if there’s any diff between the server clocks. The addition of a 10-second leeway fixes the issue:
```ruby
# lib/omniauth/login_dot_gov/id_token.rb

JWT.decode(
          id_token,
          client.idp_configuration.public_key,
          true,
          algorithm: 'RS256',
          leeway: 10
        )
```
Inspired by: https://github.com/Shopify/shopify-api-ruby/pull/1008
References:
https://github.com/jwt/ruby-jwt#expiration-time-claim

I'm happy to open a PR with this fix from [my test branch](https://github.com/MothOnMars/omniauth_login_dot_gov/blob/88354947cbd555e3c5f1c47b880561445f9212f5/lib/omniauth/login_dot_gov/id_token.rb), but there's an argument to be made for making that value configurable.

**Comment by julialeague** [comment]
Hi, @MothOnMars! Thanks a bunch for logging this issue. We would love for you to submit a PR for this update if you have the bandwidth. If not, no worries - we thank you either way!
